---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - crd.newegg.org
  resources:
  - demoapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.newegg.org
  resources:
  - demoapps/finalizers
  verbs:
  - update
- apiGroups:
  - crd.newegg.org
  resources:
  - demoapps/status
  verbs:
  - get
  - patch
  - update
